LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  rmis.ls_riskaudit
FIELDS TERMINATED BY '|'
(RISKCODE
,RISKVER
,RISKNAME
,RISKTYPE
,RISKPROP
,RISKPERIOD
,SUBRISKFLAG
,SIGNDATECALMODE
,STARTDATE DATE "yyyy-mm-dd hh24:mi:ss"
,ENDDATE DATE "yyyy-mm-dd hh24:mi:ss"
,MAKEDATE DATE "yyyy-mm-dd hh24:mi:ss"
,MAKETIME
)
