LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_new_pol_aprv
FIELDS TERMINATED BY '|'
(DATA FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,PRTNO
,APPNTNO
,APPNTNAME
,PREM
,INPUTDATE DATE "yyyy-mm-dd hh24:mi:ss"
,RESULTDATE DATE "yyyy-mm-dd hh24:mi:ss"
,ENDDATE DATE "yyyy-mm-dd hh24:mi:ss"
,RESULT
,REASON
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MAKEDATE
,MODIFYDATE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
