LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_emp_bank
FIELDS TERMINATED BY '|'
(SJRQ
,AGENTCOM
,AGENTCODE
,RATE
,RELATYPE
,MAKEDATE DATE "yyyy-mm-dd hh24:mi:ss"
,MODIFYDATE
,CHANNEL
,MANAGECOM
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
