LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_policy_info
FIELDS TERMINATED BY '|'
(SJRQ
,POLNO
,PRTNO
,APPNTNO
,APPNTNAME
,RELATIONTOAPPNT
,INSUREDNAME
,IDTYPE
,IDNO
,AGENTCODE
,AGENTCOM
,RISKCODE
,INSUYEAR
,INSUYEARFLAG
,YEARS
,PAYINTV
,PAYENDYEAR
,PAYENDYEARFLAG
,PAYYEARS
,AMNT
,PREM
,MANAGECOM
,AGENTGROUP
,POLAPPLYDATE
,SIGNDATE "replace(:SIGNDATE,'0001-01-01',null)"
,MODIFYDATE
,CHANNEL
,APPIDTYPE
,INSUREDIDTYPE
,APPIDNO
,INSUREDNO
,APPIDEFFSTARTDATE "replace(:APPIDEFFSTARTDATE,'0001-01-01',null)"
,INSUREDIDSTARTDATE "replace(:INSUREDIDSTARTDATE,'0001-01-01',null)"
,APPIDEFFENDDATE "replace(:APPIDEFFENDDATE,'0001-01-01',null)"
,INSUREDIDENDDATE "replace(:INSUREDIDENDDATE,'0001-01-01',null)"
,APPNTSEX
,INSUREDSEX
,APPNTBIRTHDAY
,BIRTHDAY
,OCCUPATIONCODE
,INSUREDOCCUP
,PROVINCE
,INSUREDPROVINCE
,CITY
,INSUREDCITY
,COUNTY
,INSUREDCOUNTY
,POSTALADDRESS
,INSUREDPOSTALADDRESS
,MOBILE
,PHONE
,INSUREDMOBILE
,INSUREDPHONE
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
