LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_pol_info_ontime
FIELDS TERMINATED BY '|'
(CONTNO
,APPNTNO
,APPNTNAME
,APPNTSEX
,APPNTSEXNAME
,APPNTBIRTHDAY DATE "yyyy-mm-dd hh24:mi:ss"
,MOBILE
,COMPANYPHONE
,HOMEPHONE
,POSTALADDRESS
,AGENTAREA
,AGENTGRPAREA
,AGENTAREAFLAG
,SIGNDATE DATE "yyyy-mm-dd hh24:mi:ss"
,PAYINTV
,ISPAYEND
,SERVICESTATE
,ISLOCK
,CONTSTATE
,INSUREDNO
,INSUREDNAME
,RELATIONTOAPPNT
,RELATIONTOAPPNTNAME
,POLNO
,RISKNAME
,AMNT
,SUMPREM
,PAYYEARS
,PAYCOUNT
,PAYTODATE DATE "yyyy-mm-dd hh24:mi:ss"
,APPNTIDTYPE
,APPNTIDNO
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,PAYMODE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
