LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_risk_info
FIELDS TERMINATED BY '|'
(SJRQ
,RISKCODE
,RISKVER
,RISKNAME
,KINDCODE
,RISKTYPE
,RISKPROP
,RISKPERIOD
,STARTDATE "replace(:STARTDATE,'0001-01-01',null)"
,ENDDATE "replace(:ENDDATE,'0001-01-01',null)"
,MINAPPNTAGE
,MAXAPPNTAGE
,MAXINSUREDAGE
,MININSUREDAGE
,SUBRISKFLAG
,RISKSHORTNAME
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
