LOAD DATA 
APPEND INTO TABLE  rmis.rmis_death_dss
FIELDS TERMINATED BY '|'
(STANDBYSTRING3
,SCODE
,SNAME
,TCODE
,TNAME
,THCODE
,THNAME
,RISKCODE
,RISKNAME
,FINANCE_SUBJECT
,MAKEDATE DATE "yyyy-mm-dd hh24:mi:ss"
,DATEID DATE "yyyy-mm-dd hh24:mi:ss"
,ACCSUM
,TIMESTAMP_TD
)
