LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_new_pol_prb
FIELDS TERMINATED BY '|'
(DATA FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,PRTNO
,SERIALNO
,ISSUETYPE
,ISSUESTATE
,MAKEDATE
,MODIFYDATE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
