LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_claim_srvc
FIELDS TERMINATED BY '|'
(SJRQ
,CLMNO
,CONTNO
,PAY
,ACCDATE "replace(:ACCDATE,'0001-01-01',null)"
,EXAMDATE "replace(:EXAMDATE,'0001-01-01',null)"
,GETDUTYKIND
,CLMSTATE
,AUDITCONCLUSION
,AUDITCONCLUPROPERTY
,SALECHNL
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
