LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_grade_info
FIELDS TERMINATED BY '|'
(SJRQ
,GRADECODE
,GRADENAME
,GRADEPROPERTY2
,CHANNEL
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
