LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_new_pol
FIELDS TERMINATED BY '|'
(PRTNO
,CONTNO
,APPNTNO
,APPNTNAME
,RISKCODE
,RISKNAME
,PREM
,STANDPREM
,FYC
,FIRSTPAYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,ENTERACCDATE DATE "yyyy-mm-dd hh24:mi:ss"
,SIGNDATE DATE "yyyy-mm-dd hh24:mi:ss"
,BANKDEALDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:BANKDEALDATE,'0001-01-01',null)"
,REASON
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,POLNO
,GETPOLDATE DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
