LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_commission_info
FIELDS TERMINATED BY '|'
(SJRQ
,COMMISIONSN
,COMMISIONBASENO
,WAGENO
,GRPCONTNO
,GRPPOLNO
,CONTNO
,POLNO
,MAINPOLNO
,MANAGECOM
,APPNTNO
,RISKCODE
,RISKVERSION
,DUTYCODE
,PAYPLANCODE
,CVALIDATE "replace(:CVALIDATE,'0001-01-01',null)"
,PAYINTV
,PAYMODE
,RECEIPTNO
,TPAYDATE "replace(:TPAYDATE,'0001-01-01',null)"
,TENTERACCDATE "replace(:TENTERACCDATE,'0001-01-01',null)"
,TCONFDATE "replace(:TCONFDATE,'0001-01-01',null)"
,TMAKEDATE "replace(:TMAKEDATE,'0001-01-01',null)"
,COMMDATE "replace(:COMMDATE,'0001-01-01',null)"
,TRANSMONEY
,TRANSSTANDMONEY
,LASTPAYTODATE "replace(:LASTPAYTODATE,'0001-01-01',null)"
,CURPAYTODATE "replace(:CURPAYTODATE,'0001-01-01',null)"
,TRANSTYPE
,COMMDIRE
,TRANSSTATE
,DIRECTWAGE
,APPENDWAGE
,GRPFYC
,CALCOUNT
,CALDATE "replace(:CALDATE,'0001-01-01',null)"
,STANDFYCRATE
,FYCRATE
,FYC
,DEPFYC
,STANDPREM
,COMMCHARGE
,COMMCHARGE1
,COMMCHARGE2
,COMMCHARGE3
,COMMCHARGE4
,GRPFYCRATE
,DEPFYCRATE
,STANDPREMRATE
,F1
,F2
,F3
,F4
,F5
,K1
,K2
,K3
,K4
,K5
,FLAG
,CALCDATE "replace(:CALCDATE,'0001-01-01',null)"
,PAYYEAR
,PAYYEARS
,YEARS
,PAYCOUNT
,SIGNDATE "replace(:SIGNDATE,'0001-01-01',null)"
,GETPOLDATE "replace(:GETPOLDATE,'0001-01-01',null)"
,BRANCHTYPE
,AGENTCOM
,BANKSERVER
,AGENTTYPE
,AGENTCODE
,AGENTGROUP
,BRANCHCODE
,BRANCHSERIES
,BRANCHATTR
,POLTYPE
,P1
,P2
,P3
,P4
,P5
,P6
,P7
,P8
,P9
,P10
,P11
,P12
,P13
,P14
,P15
,MAKEPOLDATE "replace(:MAKEPOLDATE,'0001-01-01',null)"
,CUSTOMGETPOLDATE "replace(:CUSTOMGETPOLDATE,'0001-01-01',null)"
,RISKMARK
,SCANDATE "replace(:SCANDATE,'0001-01-01',null)"
,OPERATOR
,MAKEDATE
,MAKETIME
,MODIFYDATE
,MODIFYTIME
,BRANCHTYPE2
,AGENTCODE1
,DISTICT
,DEPARTMENT
,RISKCHNL
,MAINPOLYEAR
,CHOFLAG
,HESITATE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
