LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_agnt_info
FIELDS TERMINATED BY '|'
(SJRQ
,AGENTCODE
,NAME
,SEX
,IDTYPE
,IDNO
,BIRTHDAY "replace(:BIRTHDAY,'0001-01-01',null)"
,DEGREE
,PHONE
,MOBILE
,AGENTGROUP
,JOINCOMPANYDATE "replace(:JOINCOMPANYDATE,'0001-01-01',null)"
,CAUTIONERBIRTHDAY "replace(:CAUTIONERBIRTHDAY,'0001-01-01',null)"
,OUTWORKDATE "replace(:OUTWORKDATE,'0001-01-01',null)"
,INITGRADE
,AGENTGRADE
,STARTDATE "replace(:STARTDATE,'0001-01-01',null)"
,MSTARTDATE "replace(:MSTARTDATE,'0001-01-01',null)"
,MAKEDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:MAKEDATE,'0001-01-01',null)"
,MODIFYDATE "replace(:MODIFYDATE,'0001-01-01',null)"
,CHANNEL
,MANAGECOM
,AGENTSTATE
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
