LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_get_info
FIELDS TERMINATED BY '|'
(ACTUGETNO
,CONTNO
,SHOULDDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:SHOULDDATE,'0001-01-01',null)"
,ENTERACCDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:ENTERACCDATE,'0001-01-01',null)"
,SUMGETMONEY
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
