LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_claim_info
FIELDS TERMINATED BY '|'
(CLMNO
,CONTNO
,RISKCODE
,RISKNAME
,PAYTODATE DATE "yyyy-mm-dd hh24:mi:ss"
,CUSTOMERNAME
,RPTDATE DATE "yyyy-mm-dd hh24:mi:ss"
,RGTDATE DATE "yyyy-mm-dd hh24:mi:ss"
,ENDCASEDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:ENDCASEDATE,'0001-01-01',null)"
,CLMSTATE
,CLMSTATENAME
,REALPAY
,GETFLAG
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,POLNO
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
