LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_new_pol_unpay
FIELDS TERMINATED BY '|'
(DATA FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,PRTNO
,ENTERACCSTATE
,ENTERACCDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:ENTERACCDATE,'0001-01-01',null)"
,REMIND
,MAKEDATE
,MODIFYDATE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
