LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_payment_info_unscss
FIELDS TERMINATED BY '|'
(SERIALNO
,POLNO
,BANKDEALDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:BANKDEALDATE,'0001-01-01',null)"
,REASON
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:MODIFYDATE,'0001-01-01',null)"
,PAYCODE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
