LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_bank_org
FIELDS TERMINATED BY '|'
(SJRQ
,AGENTCOM
,NAME
,MANAGECOM
,UPAGENTCOM
,BANKCODE
,BANKTYPE
,MAKEDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:MAKEDATE,'0001-01-01',null)"
,MODIFYDATE
,CHANNEL
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
