LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_sale_org
FIELDS TERMINATED BY '|'
(SJRQ
,AGENTGROUP
,NAME
,MANAGECOM
,FOUNDDATE
,ENDDATE "replace(:ENDDATE,'0001-01-01',null)"
,UPBRANCH
,MODIFYDATE
,CHANNEL
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
