LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_endor_reduce
FIELDS TERMINATED BY '|'
(SJRQ
,CONTNO
,EDORACCEPTNO
,APPNTNO
,INSUREDNAME
,RISKCODE
,GETMONEY
,APPROVEDATE "replace(:APPROVEDATE,'0001-01-01',null)"
,SALECHNL
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
