LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_appnt_info
FIELDS TERMINATED BY '|'
(DATA FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,APPNTNO
,APPNTNAME
,APPNTSEX
,APPNTBIRTHDAY DATE "yyyy-mm-dd hh24:mi:ss" "replace(:APPNTBIRTHDAY,'0001-01-01',null)"
,IDTYPE
,IDNO
,IDEFFSTARTDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:IDEFFSTARTDATE,'0001-01-01',null)"
,IDEFFENDDATE DATE "yyyy-mm-dd hh24:mi:ss" "replace(:IDEFFENDDATE,'0001-01-01',null)"
,ISLONGTERM
,HASSOCIALSECURITY
,DEGREE
,MARRIAGE
,LICENSE
,LICENSETYPE
,ZIPCODE
,POSTALADDRESS
,PHONE
,HOMEZIPCODE
,HOMEADDRESS
,HOMEPHONE
,COMPANYZIPCODE
,COMPANYADDRESS
,COMPANYPHONE
,GRPNAME
,OCCUPATIONCODE
,MOBILE
,EMAIL
,NATIVEPLACE
,RGTADDRESS
,PROVINCECODE
,PROVINCENAME
,CITYCODE
,CITYNAME
,COUNTYCODE
,COUNTYNAME
,STREETPOSTALADDRESS
,MODIFYDATE
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
