LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_endor_info
FIELDS TERMINATED BY '|'
(EDORACCEPTNO
,CONTNO
,POLNO
,EDORAPPDATE DATE "yyyy-mm-dd hh24:mi:ss"
,EDORVALIDATE DATE "yyyy-mm-dd hh24:mi:ss"
,EDORTYPENAME
,EDORSTATE
,EDORSTATENAME
,GETMONEY
,MANAGECOM
,AGENTGROUP
,AGENTCODE
,BRANCHTYPE
,BRANCHTYPE2
,MODIFYDATE DATE "yyyy-mm-dd hh24:mi:ss"
,EDORTYPE
,INSUREDNO
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
