LOAD DATA 
CHARACTERSET UTF8
APPEND INTO TABLE  mid.crm_insd_grp
FIELDS TERMINATED BY '|'
(SJRQ
,GRPCONTNO
,CONTNO
,PRTNO
,APPNTNAME
,APPNTNO
,INSUREDNAME
,INSUREDSEX
,MOBILE
,HOMEPHONE
,IDTYPE
,IDNO
,IDEFFSTARTDATE "replace(:IDEFFSTARTDATE,'0001-01-01',null)"
,IDEFFENDDATE "replace(:IDEFFENDDATE,'0001-01-01',null)"
,PROVINCE
,CITY
,COUNTY
,POSTALADDRESS
,BIRTHDAY
,OCCUPATIONTYPE
,OCCUPATIONCODE
,AGENTCODE
,AGENTCOM
,CHANNEL
,REMARK
,POLAPPLYDATE "replace(:POLAPPLYDATE,'0001-01-01',null)"
,SIGNDATE
,MODIFYDATE
,MANAGECOM
,AGENTGROUP
,BRANCHTYPE2
,UPD_DT FILLER DATE "yyyy-mm-dd hh24:mi:ss"
,BATCHNO
)
